version: '3.4'

services:
  carteiradecambiodb:
    container_name: carteiradecambiodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
        - mongo_data:/data/db

  carteiradecambio:
    container_name: carteiradecambio
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://carteiradecambiodb:27017"
    depends_on:
      - carteiradecambiodb
    ports:
      - "8001:80"
